// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mndwifizvvmscndzzhxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZHdpZml6dnZtc2NuZHp6aHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTAwNzEsImV4cCI6MjA1NTgyNjA3MX0.0uKudaahwFWmdm-X_F8qDW077InLMi-yO7XrDPnMSlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);